### ISSUE TITLE
Allow Local Network Permission Not Triggered on 2.21.0

### ISSUE THREAD

**Issue by benshepherd-ps** [stripe/stripe-terminal-ios#238] opened 2023-06-19 16:02 UTC
## Summary
When building our app with SDK 2.21.0 and doing a fresh install, attempting to connect to an internet reader (WisePOS E) never triggers the iOS permission to allow local network access. Because it is never triggered, the app does not show it in the device's Privacy settings as an option to enable. This blocks all connections and there is no workaround. Re-installing SDK 2.20.2, deleting the app, reinstalling it, and attempting to connect to the internet reader works as expected.

## iOS version
16.5

## Installation method
SPM

## SDK version
2.21.0

## Other information
When first experiencing the problem, I tried changing the device's DNS settings to use Cloudflare (even though this has never been required on this network previously) and that didn't work. I also tried multiple times to delete/reinstall the app and restart the internet reader. All diagnostic checks on the reader were fine.

**Comment by bric-stripe** [comment] 2023-06-20 19:09
@benshepherd-ps I've been unable to reproduce the same behavior and unaware of any changes in to 2.21.0 that could explain changes here. I tried removing the app (also tried changing the bundle ID to ensure I got a fresh check) and am using the same OS version. 

Do you see the same behavior if you use the example app? Could you provide the logs that get reported via the [log listener](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(cm)setLogListener:)?

**Comment by benshepherd-ps** [comment] 2023-06-23 16:10
Thanks for the response. Yes, we do see the location prompt on top but after accepting that permission we never saw the local network permission. We'll try the example app and the log listener.

**Comment by bric-stripe** [comment] 2023-09-13 18:35
@benshepherd-ps any updates? I'm going to close this out but re-open if you found anything to follow up on here.

**Closed by bric-stripe** 2023-09-13 18:35 UTC
