### ISSUE TITLE
SDK Does not fire Card Removed event during a transaction and does not fire the next card inserted

### ISSUE THREAD

**Issue by blairio** [stripe/stripe-terminal-ios#114] opened 2021-09-23 22:47 UTC
## Summary
On the Wisepad 3 if the card is removed during the transaction (on the pin pad screen for example) the SDK does not fire the Card Removed event. Subsequently, the next Card Inserted event will not fire.

## Code to reproduce
Using the [Stripe Terminal Example iOS App](https://github.com/stripe/stripe-terminal-ios/tree/master/Example) at 3b2d0ea678150fdcae0df4bfa7d7f3aef4f63ade

See Video:  https://drive.google.com/file/d/1ur_e9v4T1SCv6FLjBBXYySZOQnzkjS5y/view?usp=sharing

00:14 Card inserted and Card Inserted Event 👍 
00:21 Card removed, but **no Card Removed event** 👎 (Generic "command was cancelled" was returned in the delegate)
00:32 Card inserted, but **no Card Inserted event** 👎 
00:35 Card removed, and Card Removed Event 👍 
00:38 Card Inserted and Card Inserted Event 👍 
00:39 Card removed, and Card Removed Event 👍 

Note, if a new payment intent had been started at 00:32 it still does not report the event.

## iOS version
iPad iOS 14.8

## Installation method
Ran the example app

## SDK version
The version included in the example app at 3b2d0ea678150fdcae0df4bfa7d7f3aef4f63ade

## Other information

![IMG_0082](https://user-images.githubusercontent.com/198135/134593270-4339569e-5a0f-41cc-a008-f8a7dbda3cd0.PNG)

![IMG_0083](https://user-images.githubusercontent.com/198135/134593291-cabf24e3-5c68-41b9-baae-31f58d204a00.PNG)

**Comment by bric-stripe** [comment] 2021-09-24 16:52
thanks for the detailed report and video and all 👍 ack'ing that we've reproduced and made some sense of things here but it may be a bit before we get fixes in. Specifically it looks like internally we can't yet differentiate when removing the card during PIN entry vs. when canceling the PIN entry with the red x, so we'll likely need to work with BBPOS on that (this is why it's reporting canceled instead of `cardRemoved` error). I'm still investigating the missing removed/inserted events.

**Comment by blairio** [comment] 2021-09-24 17:51
Thanks!

**Comment by bric-stripe** [comment] 2021-10-04 19:33
hi @blairio we're looking to get the missing `CardRemoved`/`CardInserted` events fixed up in our next release currently scheduled for ~Oct 18. So the collect call will still report `Canceled` when card removed during PIN prompt, instead of `CardRemoved` (for now), but the missing events should be addressed.

**Comment by bric-stripe** [comment] 2023-10-03 22:40
Sorry for delay closing this out but this should be fixed now. Removing the card early should now emit the `didRequestReaderDisplayMessage` with [`CardRemovedTooEarly`](https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPReaderDisplayMessage.html#/c:@E@SCPReaderDisplayMessage@SCPReaderDisplayMessageCardRemovedTooEarly) and the reader should restart collection.

**Closed by bric-stripe** 2023-10-03 22:40 UTC
