### ISSUE TITLE
didReportUnexpectedReaderDisconnect not firing

### ISSUE THREAD

**Issue by a428tm** [stripe/stripe-terminal-ios#193] opened 2022-12-04 05:48 UTC
## Summary
I expect `didReportUnexpectedReaderDisconnect` to fire when the reader disconnects, but it doesn't seem to be doing so.

Stripe M2 + iPhone 13 mini are the devices I am using

## Code to reproduce
This is not firing when the bluetooth device is turned off. Stripe M2 device

```
extension BLEManager: TerminalDelegate {
    func terminal(_ terminal: Terminal, didChangeConnectionStatus status: ConnectionStatus) {
        logger.log("didChangeConnectionStatus")
    }
    
    func terminal(_ terminal: Terminal, didChangePaymentStatus status: PaymentStatus) {
        logger.log("didChangePaymentStatus")
    }
    
    func terminal(_ terminal: Terminal, didReportUnexpectedReaderDisconnect reader: Reader) {
        // Consider displaying a UI to notify the user and start rediscovering readers
        logger.log("didReportUnexpectedReaderDisconnect")
        
        let displayIdentifier = reader.label ?? reader.serialNumber
        
        logger.log("didReportUnexpectedReaderDisconnect - reader disconnected from \(displayIdentifier)")
        
        self.showAlertUnexpectedReaderDisconnect = true
        
        self.viewState = .preDiscovery
        self.discoverReaders()
    }
}
```

## iOS version
iOS 16 - iPhone 13 mini

## Installation method
Apple Swift Packages

## SDK version
2.14.0

**Comment by bric-stripe** [comment] 2022-12-05 14:45
Hi @a428tm I'm unable to reproduce this. Does it reproduce 100% of the time for you? Are you able to reproduce it with the example app in the repo?

One thing we've seen is since Terminal only holds a weak reference to the provided `TerminalDelegate` if your application doesn't have a persistent strong reference it will be released and then be nil'd in the SDK. If that happened you also wouldn't be getting the didChange[Connection|Payment] statuses though either. 

If you're using the auto-reconnect feature on the BluetoothConnectionConfig the unexpectedDisconnect won't fire and your `ReconnectionDelegate` should receive the `didStartReaderReconnect` and related events and then the `terminalDidFailReaderReconnect` when it stops retrying.

If it's not any of those things can you add a serial number of a reader that you hit the problem with and rough timing of when it occurred? We can then check on our logging to see if anything stands out.

**Comment by a428tm** [comment] 2022-12-05 23:23
@bric-stripe 
Thank you for the quick response.

I am no expect in Swift, so I am not sure if the following is true or not, but the app gets information from the device related to card tap/insert/swipe/remove etc. and process the payment without any issue.

> One thing we've seen is since Terminal only holds a weak reference to the provided TerminalDelegate if your application doesn't have a persistent strong reference it will be released and then be nil'd in the SDK. If that happened you also wouldn't be getting the didChange[Connection|Payment] statuses though either.

Battery warning, battery level information and detail and `didReportUnexpectedReaderDisconnect` are the ones that I am not getting any response on.

Please see serial number of the readers that don't send me this data (I think all 5 I have this issue) -
1. Stripe M2 - STRM26142073981
2. CBBPOS Chipper™ 2X BT - CHB202003016037

**Comment by bric-stripe** [comment] 2023-10-03 22:59
closing out old issues, please re-open if have new information for this one.

**Closed by bric-stripe** 2023-10-03 22:59 UTC
