### ISSUE TITLE
Tipping Configuration on iOS

### ISSUE THREAD

**Issue by RichAppz** [stripe/stripe-terminal-ios#153] opened 2022-05-03 19:43 UTC
## Summary
There seems to be an issue setting configuration for the very first time on a WisePad 3. If you set up fixed or percentages first then the device returns a no-tipping config. If you then set up Smart tipping, this is returned. After this you can set fixed / percentages and all is fine.

## iOS version
iOS 15

## Installation method
Cocoapod

## SDK version
v2.7.0

**Comment by mkrager-stripe** [comment] 2022-05-04 19:57
Hey Rich!
We are aware of an issue that fits your descriptions: https://github.com/stripe/stripe-terminal-android/issues/227#issue-1212022187 

In summary, we are seeing an issue with how `Location`'s cache, which is causing stale tipping configurations to be sent over. Here is a summary of what we were seeing for another user:
- On 13:01:33 BST - the Android SDK fetches the tipping config right after you connect your WP3 reader to your POS app. Our backend gets tipping configs from a configuration override set to a [Location](https://stripe.com/docs/api/terminal/locations). The Location object is cached in our backend for a minute.
- On 13:02:17 BST - you create a new Configuration object with percentage tipping configs.
- On 13:02:19 BST - you set the configuration_override for your Location with the new [Configuration](https://stripe.com/docs/api/terminal/configuration/object?Do=).
- On 13:02:27 BST - the Android SDK fetches tipping config again but our backend sends stale tipping configs. This is because our backend caches the Location object for a minute. The configuration_override for the Location is stale so stale tipping configs are sent.

Just so I can confirm that what you are seeing is the same issue, could you provide the following:
- Logs from your POS app if possible
- Your WisePad 3 reader serial number used to reproduce this issue (e.g. WPC3230270000325 - can be found at the back of your WisePad 3 reader)
- Approximately when you reproduced this issue (e.g. 10AM BST on April 22)

If your issue is the same, we recommend updating the Configuration object instead of creating a new one. See our API documentation for [updating a Configuration](https://stripe.com/docs/api/terminal/configuration/update).

**Comment by bric-stripe** [comment] 2022-11-11 16:28
Closing out this older issue but please re-open or create a new issue if still running in to issues here.

**Closed by bric-stripe** 2022-11-11 16:28 UTC
