### ISSUE TITLE
Crash Error: [SCPLogForwardingController accountId] 

### ISSUE THREAD

**Issue by moa-amenitiz** [stripe/stripe-terminal-ios#317] opened 2024-07-27 12:09 UTC
## Code to reproduce

 It is a crash log so I do not have any reproducible state. But it affect a lot of users on our end and the crash log is quite precise.
## iOS version
 - 17.5.1
 - 17.3.1

## Installation method
 - SPM

## SDK version
- 3.7.0

## Other information
Crash Log From Firebase Crashlyics: 

``` 
Crashed: fmdb.<SCPFMDatabaseQueue: 0x302e559e0>
EXC_BREAKPOINT 0x00000001930b9628
 ```

```          
Crashed: fmdb.<SCPFMDatabaseQueue: 0x302a6c8d0>
0  libdispatch.dylib              0x13628 __DISPATCH_WAIT_FOR_QUEUE__ + 488
1  libdispatch.dylib              0x1315c _dispatch_sync_f_slow + 148
2  StripeTerminal                 0x165194 -[SCPLogForwardingController accountId] + 140
3  StripeTerminal                 0x15f0c4 -[SCPLog account] + 32
4  StripeTerminal                 0xf690 -[SCPTrace initWithTraceContext:service:method:request:] + 216
5  StripeTerminal                 0x1011d8 +[SCPLogRecordStore internalTraceForContext:error:] + 448
6  StripeTerminal                 0x100410 __41-[SCPLogRecordStore deleteStateIfUnused:]_block_invoke + 188
7  StripeTerminal                 0x159ce4 __33-[SCPFMDatabaseQueue inDatabase:]_block_invoke + 52
8  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
9  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
10 StripeTerminal                 0x159c94 -[SCPFMDatabaseQueue inDatabase:] + 100
11 StripeTerminal                 0x10032c -[SCPLogRecordStore deleteStateIfUnused:] + 164
12 StripeTerminal                 0x165e24 -[SCPLogForwardingController didFinishSendingBatchForState:didError:] + 64
13 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
15 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
16 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
17 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
18 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
19 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
20 libsystem_pthread.dylib        0x10cc start_wqthread + 8
```

**Comment by bric-stripe** [comment] 2024-07-31 23:22
Hi, just acknowledging that we're investigating this but no updates other than this seems to be a deadlock. Will update the issue when we know more.

**Comment by bric-stripe** [comment] 2024-08-06 16:50
@moa-amenitiz we just released [3.8.1](https://github.com/stripe/stripe-terminal-ios/releases/tag/3.8.1) with a fix for this. Thanks for reporting it! Closing this out but reopen if still running in to issues with 3.8.1+

**Comment by bric-stripe** [comment] 2024-08-07 16:23
sorry for the thrash, we found another case that could lead to a deadlock here and we're working on a 3.8.2 with the fix for that. We'll keep this issue updated.

**Comment by bric-stripe** [comment] 2024-08-08 17:35
3.8.2 is out that has the fix for the last remaining deadlock. Re-open if still seeing any issues though.

**Comment by moa-amenitiz** [comment] 2024-08-09 09:25
Thanks we will update to the new sdk then!

**Comment by moa-amenitiz** [comment] 2024-08-10 21:58
@bric-stripe It seems that some crashes still occurs around the SCPLogForwardingController. I am not sure if it is link to this deadlock issue but I am putting it here. 

```
       Crashed: fmdb.<SCPFMDatabaseQueue: 0x302a80ae0>
0  libdispatch.dylib              0x13628 __DISPATCH_WAIT_FOR_QUEUE__ + 488
1  libdispatch.dylib              0x1315c _dispatch_sync_f_slow + 148
2  StripeTerminal                 0x35618 scpDispatchSyncIfNecessary + 84
3  StripeTerminal                 0x173a48 -[SCPLogForwardingController accountId] + 148
4  StripeTerminal                 0x16d71c -[SCPLog account] + 32
5  StripeTerminal                 0xfb08 -[SCPTrace initWithTraceContext:service:method:request:] + 216
6  StripeTerminal                 0x10ac4c +[SCPLogRecordStore internalTraceForContext:error:] + 448
7  StripeTerminal                 0x109e84 __41-[SCPLogRecordStore deleteStateIfUnused:]_block_invoke + 188
8  StripeTerminal                 0x16833c __33-[SCPFMDatabaseQueue inDatabase:]_block_invoke + 52
9  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
10 libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
11 StripeTerminal                 0x1682ec -[SCPFMDatabaseQueue inDatabase:] + 100
12 StripeTerminal                 0x109da0 -[SCPLogRecordStore deleteStateIfUnused:] + 164
13 StripeTerminal                 0x1746fc -[SCPLogForwardingController didFinishSendingBatchForState:didError:] + 64
14 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
15 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
16 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
17 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
18 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
19 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
20 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
21 libsystem_pthread.dylib        0x10cc start_wqthread + 8        
```

**Comment by bric-stripe** [comment] 2024-08-12 14:59
Thanks for the fresh stack trace. We're working on a 3.8.3 update that we believe fixes the root cause of the issues. Thanks for your patience on this, it's been a tricky one.

**Comment by bric-stripe** [comment] 2024-08-12 17:05
[3.8.3](https://github.com/stripe/stripe-terminal-ios/releases/tag/3.8.3) is available now with a fix for the root cause.

**Closed by bric-stripe** 2024-08-12 17:05 UTC
