### ISSUE TITLE
[Stripe M2] Bluetooth device disconnected

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [stripe/stripe-terminal-ios#120] opened 2021-11-01 03:41 UTC
## Summary
When the app tries to connect to M2, it sometimes reports this error.

## iOS version
14.6/iPad Mini 4

## Installation method
Cocapods

## SDK version
SDK: 2.2.0

## Other information
![image](https://user-images.githubusercontent.com/65152333/139618627-07cf2e2f-9ac8-4eb3-9868-c6549990dea1.png)
![image](https://user-images.githubusercontent.com/65152333/139618658-eeabdac9-f154-4798-9356-6879346a2237.png)

**Comment by jil-stripe** [comment] 2021-11-01 17:00
Thanks for writing in! We found logs that matched up with this error, and it looks like in those cases the reader gets disconnected because the battery level is critically low. We're working on improving the error experience here but in the meantime, if you see this again, reconnecting while the reader is plugged into power should prevent you from seeing this.

**Comment by blairio** [comment] 2021-11-04 00:26
We have seen this with the Wisepad 3 as well when the battery is critically low.
We were wondering is 3230 always caused by a low battery or is there other disconnect reasons that would report 3230?

Thanks

**Comment by jil-stripe** [comment] 2021-11-04 13:56
3230 (`SCPErrorBluetoothDisconnected`) is returned whenever there's an unexpected disconnection from a bluetooth reader, which can happen in a few different scenarios, but you're probably most likely to see it when the battery gets critically low. However, If the reader gets too far away from the iOS device or if the reader is physically destroyed or if there's significant bluetooth interference, you'll also see this error.

**Comment by blairio** [comment] 2021-11-04 15:20
Thanks

**Comment by blairio** [comment] 2022-03-10 22:16
I left an M2 device plugged in and connected to an iPad for a week. When I came back it had disconnected and would not reconnect. The iPad reportedError 3230 and would not show up in discovery on that iPad or other iPads. Pressing the M2 power button would display 4 green lights, but still no connection. It was plugged into power the whole time. After using a paperclip to reset it we were able to reconnect and it reported 92% battery.

**Comment by bric-stripe** [comment] 2022-11-10 17:16
👋 reviewing old tickets and leaving this one open for now but I'm hopeful we can close it out after verifying it's no longer an issue in the latest M2 firmware.

But also want to call out that the M2 will disconnect after 24 hours as part of PCI compliance (it does a hardware reset that disconnects it from the iOS device), so the fact that it disconnected during that week isn't surprising, but the inability to discover/reconnect until it was restarted is concerning.

And while here, regarding the 24 hour disconnect, the new-ish [auto reconnect option for Bluetooth readers](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=bluetooth#2.-automatically-attempt-reconnection) will help with that and would attempt to automatically reconnect after the disconnect.

**Comment by bric-stripe** [comment] 2022-11-17 18:07
I've been left an old iPhone 6s connected to an M2 all week and confirmed when using the Bluetooth auto reconnect in the connection configuration it successfully reconnects each day and when I just explicitly disconnected now was able to discover the reader and reconnect right away. I'll continue to leave this reader and device in this state and will check on them to try to reproduce. I'm going to close this issue but will re-open if I run in to anything odd. And please re-open if anyone is still hitting this and has more info to add (repro steps would be great but a serial and rough timing for when an issue was hit would be fine).

**Closed by bric-stripe** 2022-11-17 18:07 UTC
