### ISSUE TITLE
App crashes on iOS 13.3.1

### ISSUE THREAD

**Issue by TimberGan** [stripe/stripe-terminal-ios#73] opened 2020-02-10 11:18 UTC
When running the Terminal app on iOS 13.3, everything works as expected. However, a change occurred in version **13.3.1** which produces the below error:
`dyld: Library not loaded: @rpath/CreditFS.framework/CreditFS
  Referenced from: /private/var/containers/Bundle/Application/753EAC76-0CD1-4ABC-B21B-6418B9BC9CDC/CreditFSModuleTestDemo.app/CreditFSModuleTestDemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/753EAC76-0CD1-4ABC-B21B-6418B9BC9CDC/CreditFSModuleTestDemo.app/Frameworks/CreditFS.framework/CreditFS: code signature invalid for '/private/var/containers/Bundle/Application/753EAC76-0CD1-4ABC-B21B-6418B9BC9CDC/CreditFSModuleTestDemo.app/Frameworks/CreditFS.framework/CreditFS'

	/private/var/containers/Bundle/Application/753EAC76-0CD1-4ABC-B21B-6418B9BC9CDC/CreditFSModuleTestDemo.app/Frameworks/CreditFS.framework/CreditFS: stat() failed with errno=25
(lldb) `
all programs are this problem ,plz help me

**Comment by jil-stripe** [comment] 2020-02-24 17:15
@TimberGan,
This looks like a duplicate of #72 -- I'm hoping we can consolidate discussion there.
Thanks for raising the issue!
James

**Closed by jil-stripe** 2020-02-24 17:15 UTC
